// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function GetKeyWordStatsConfig() {
  return window['go']['main']['App']['GetKeyWordStatsConfig']();
}

export function GetWordFreqStatsConfig() {
  return window['go']['main']['App']['GetWordFreqStatsConfig']();
}

export function RunKeyWordStats() {
  return window['go']['main']['App']['RunKeyWordStats']();
}

export function RunWordFreqStats() {
  return window['go']['main']['App']['RunWordFreqStats']();
}

export function SelectKeyWordInputDir() {
  return window['go']['main']['App']['SelectKeyWordInputDir']();
}

export function SelectKeyWordOutputDir() {
  return window['go']['main']['App']['SelectKeyWordOutputDir']();
}

export function SelectWordFreqInputDir() {
  return window['go']['main']['App']['SelectWordFreqInputDir']();
}

export function UpdateKeyWordStatsConfig(arg1) {
  return window['go']['main']['App']['UpdateKeyWordStatsConfig'](arg1);
}

export function UpdateWordFreqStatsConfig(arg1) {
  return window['go']['main']['App']['UpdateWordFreqStatsConfig'](arg1);
}
