// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearMemory():Promise<void>;

export function GetKeyWordStatsConfig():Promise<backend.KeyWordStatConfig>;

export function GetWordFreqStatsConfig():Promise<backend.WordFreqStatConfig>;

export function RunKeyWordStats():Promise<string>;

export function RunWordFreqStats():Promise<string>;

export function SelectKeyWordInputDir():Promise<string>;

export function SelectKeyWordOutputDir():Promise<string>;

export function SelectWordFreqInputDir():Promise<string>;

export function UpdateKeyWordStatsConfig(arg1:backend.KeyWordStatConfig):Promise<void>;

export function UpdateWordFreqStatsConfig(arg1:backend.WordFreqStatConfig):Promise<void>;
